// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUqZkR1lixjhEq6prCtOIm2oFktDxfgyU',
    appId: '1:488530073470:web:a0cd3bae1e24415e5ac52f',
    messagingSenderId: '488530073470',
    projectId: 'chatapp-7535b',
    authDomain: 'chatapp-7535b.firebaseapp.com',
    storageBucket: 'chatapp-7535b.firebasestorage.app',
    measurementId: 'G-2K2CMJL1WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMOlbzjtLUJ6V8Tg3eYaO_QzTdQaHplPA',
    appId: '1:488530073470:android:ffc774ae83ad53c75ac52f',
    messagingSenderId: '488530073470',
    projectId: 'chatapp-7535b',
    storageBucket: 'chatapp-7535b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1uU0PmSy5Jk7QCvdd0uQf7_Atpr1qbC4',
    appId: '1:488530073470:ios:2c4448fc46479e725ac52f',
    messagingSenderId: '488530073470',
    projectId: 'chatapp-7535b',
    storageBucket: 'chatapp-7535b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1uU0PmSy5Jk7QCvdd0uQf7_Atpr1qbC4',
    appId: '1:488530073470:ios:2c4448fc46479e725ac52f',
    messagingSenderId: '488530073470',
    projectId: 'chatapp-7535b',
    storageBucket: 'chatapp-7535b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUqZkR1lixjhEq6prCtOIm2oFktDxfgyU',
    appId: '1:488530073470:web:a0cd3bae1e24415e5ac52f',
    messagingSenderId: '488530073470',
    projectId: 'chatapp-7535b',
    authDomain: 'chatapp-7535b.firebaseapp.com',
    storageBucket: 'chatapp-7535b.firebasestorage.app',
    measurementId: 'G-2K2CMJL1WP',
  );

}